### ISSUE TITLE
Qloader

### ISSUE THREAD

**Issue by OrJiNaL33** [vic4key/QLoader#1]
selamün aleyküm için emegine saglık birkaç problem var yardımcı olurmusunuz teşekkürler teplate patent dosyasını düzenleyebilirmisiniz

Hi there, thanks for the Qdloader, there are a few problems, can you help me, thank you, can you edit the teplate patent file?

The patent has set a template for testing, but I can't add more than one 2-3-4-5 patch.

**Comment by vic4key** [comment]
Hi @OrJiNaL33,

What do you mean that `cannot add more than one 2-3-4-5 patch`? If you mean is adding new patches on QLoader's UI, it does not support now and currently in-progress. Temporary, you can add by editing the JSON file directly by a text editor, then re-load it into QLoader. As the below, I added new patches `30.1, 30.2, 30.3`.

![image](https://user-images.githubusercontent.com/5672864/234154693-26997cbe-4d17-4123-abec-e25bba0235c3.png)

**Comment by OrJiNaL33** [comment]
Thanks, I didn't explain well my problem
1 patch ok 2-3-4-5-6 patch bat
Other patches don't work after 1 patch

**Comment by vic4key** [comment]
Could you show me the log result after launched?
And you have to make sure as the following:
1. All patches are valid. It means all patches can be found in the executable file.
2. All patches are not conflict. It means they're affected to each other.
 >- Eg. Bytes: 11 22 33 44. Pat
 >- Patch 1: 11 22 => FF FF (after finished Patch 1, bytes are now FF FF 33 44)
 >- Patch 2: 22 33 => FF FF (Patch 2 could not be found)

**Comment by OrJiNaL33** [comment]
Thanks. It's like it's done, but there are some errors, the patch doesn't apply all of them, I don't understand if it conflicts with each other.
[https://res-h3.public.cdn.office.net/assets/mail/file-icon/png/generic_16x16.png]loader.template.json<https://1drv.ms/u/s!Ah7ktCaoTTdygkDkzD-x9eo1l6ci>
<https://1drv.ms/i/s!Ah7ktCaoTTdygkGH9WOFZ5MWqFwe>
[https://sjqfow.db.files.1drv.com/y4mJt-k37vJuHHXOB5-DvEkYZa393Ny8_jgtbaQMqtgIx0Dj_Znu-qNb-Fyoqm2MdepiA4v01KdkUiHFwsEuEvK57h3KBYgQnG8Dvw8zvH-5usk6TDzZNVVUHPrmaIIzCOzENvk--ApGvGcyxGcius09cSbGIeLPxvckoNSICRuIK-_s-OcduIH2bfQxFJFYdrPZZ71W-Z0bG1jOnt8VVKK1w?width=200&height=150&cropmode=center]
[https://res.cdn.office.net/assets/mail/file-icon/png/cloud_blue_16x16.png]Adsız.jpg
<https://1drv.ms/i/s!Ah7ktCaoTTdygkI8aJyA-uXlw-o9>
[https://sj96ga.db.files.1drv.com/y4mfy0-J0k1g0X25M2zsdsW87XElZYGREUzKcdEmbj4KTV0P37Jclag7zUpxbMK4UAdo8m3mkHY9SnlGhI7eC2cTENf89GAEokVimPOfSXNDEUGxuFthH4KqAusGXPDc6FV-3FKBP2Vp4WewfWsuJwWIaIZJn6DzqJ6hqLf6sQw-81geIRYG24buFyEmdjRQlCvKoJ_EYJCb_eHB091mewzOA?width=200&height=150&cropmode=center]
[https://res-h3.public.cdn.office.net/assets/mail/file-icon/png/cloud_blue_16x16.png]AdsızX.jpg
<https://1drv.ms/i/s!Ah7ktCaoTTdygkOknfZkSGlyFWCU>
[https://sj8vjq.db.files.1drv.com/y4mqzZXtfVuSBlS_y-PME-9kJfFSMq1aBKfCCnjJpNt4Eoytz_TztRKvZE0Etn3ZELFutI2SElCD3GgzZBojZAwyekLkgEoly7S9RmQ7zwYTEvQrIaDcH8xghwoTf_Hwei-IUUv3tleZWpUGhpLTZhkttcmUfJoEPMvj37RS9JIsO_hJZu1V6DCv8XnLtHHoU4rc0mvNlo3AFU-fSTat9aKVg?width=200&height=150&cropmode=center]
[https://res.cdn.office.net/assets/mail/file-icon/png/cloud_blue_16x16.png]Adsızxx.jpg
<https://1drv.ms/i/s!Ah7ktCaoTTdygkQYdsirMy70CfO5>
[https://sjpwaq.db.files.1drv.com/y4m9AhE5BKzQRTzhVqLRKVqJA94ftK025_NzYN178mSLj0F7GUeho1_DtVNpL5YMTt4OSyiIsDbTRmHueh1CA0jd7tSX0BJFH-sHX8qOPbUn2mLe6UGPIBDV0suVLNwt6K6lPZlPjYOCn6LHfG9Tf-faqLjc_44s5VLb3qyKPd7KJbhfHDV1wQQkULjghomv8c38rYttCAjVLYqbFyfilSO1Q?width=200&height=150&cropmode=center]
[https://res-h3.public.cdn.office.net/assets/mail/file-icon/png/cloud_blue_16x16.png]Adsızxxx.jpg
<https://1drv.ms/i/s!Ah7ktCaoTTdygkU49JX0mFREvWM0>
[https://sj9ldg.db.files.1drv.com/y4mqtvOavLByMly1k8NU85wSwV1i6323nXya6vo8ZhXns2rKVw6QLztijPpfDPWDsW5Kar8ud0pfePXHdXUO42cD0K3kCMggsbW7HBFK3CFx-EatjJHG_kNmA0N6ZCkhRfvEQp11UrZ96hISUOyp0uLwIr6RRE-zB7M5xyvVligeUTWglGAS1Csc7ityUicLfhFuoSE5ybbQRexyk6JJI8QJg?width=200&height=150&cropmode=center]
[https://res.cdn.office.net/assets/mail/file-icon/png/cloud_blue_16x16.png]Adsızz.jpg


________________________________
Gönderen: Vic P. ***@***.***>
Gönderildi: 26 Nisan 2023 Çarşamba 07:30
Kime: vic4key/QLoader ***@***.***>
Bilgi: OrJiNaL33 ***@***.***>; Mention ***@***.***>
Konu: Re: [vic4key/QLoader] Qloader (Issue #1)


Could you show me the log result after launched?
And you have to make sure as the following:

  1.  All patches are valid. It means all patches can be found in the executable file.
  2.  All patches are not conflict. It means they're affected to each other.

  *   Eg. Bytes: 11 22 33 44. Pat
  *   Patch 1: 11 22 => FF FF (after finished Patch 1, bytes are now FF FF 33 44)
  *   Patch 2: 22 33 => FF FF (Patch 2 could not be found)

**Comment by OrJiNaL33** [comment]
Thanks. It's like it's done, but there are some errors, the patch doesn't apply all of them, I don't understand if it conflicts with each other.
PM sent master Thank you for your interest

**Comment by vic4key** [comment]
You can check your patches are conflict or not by launch one by one, details as the following:

1. Disable all patches.
2. Enable Patch 1.
3. Press launch.
4. The log window showing found address and patched succeed.
5. Disable Patch 1.

Loop the steps 2 to 5 to test for remaining patches (Patch 2, 3, ...).

_Note: Or for quick, you can select more than one patch at once for testing instead of one. Eg. Enable 5 patches at once._

**Comment by OrJiNaL33** [comment]
hello master, thank you for your attention, it works smoothly, thank you for your effort

**Comment by vic4key** [comment]
Yes. Hope it's useful to you. Have fun with the tool.
