### ISSUE TITLE
Build issue: missing vu library

### ISSUE THREAD

**Issue by greenozon** [vic4key/QLoader#2]
It is not possible to build the tool, at least one lib is missing:

![image](https://github.com/vic4key/QLoader/assets/765343/fc8078b7-a54e-45c0-a21c-7d2154ceb920)

**Comment by vic4key** [comment]
@greenozon Please take a look at the section `Development` @ https://github.com/vic4key/QLoader#development
You need to install Vutils (very simple to install @ https://github.com/vic4key/Vutils#installation) to build the solution.

**Comment by greenozon** [comment]
Thanks
all clear, closing
